# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in chimera_mud-server.gemspec.
gemspec

group :development do
  gem "chimera_mud-core", path: "../core"
  gem "sqlite3"
end

# To use a debugger
# gem 'byebug', group: [:development, :test]
